name: Main Branch Protection

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    # Only run on upstream better-auth repo, not on forks
    if: github.repository == 'better-auth/better-auth'
    steps:
      - name: Check branch
        run: |
          if [[ ${GITHUB_HEAD_REF} != canary ]] && ! [[ ${GITHUB_HEAD_REF} =~ ^v[0-9]+\.[0-9]+\.[0-9]+-staging$ ]];
          then
            echo "Error: Pull request must come from 'canary' or 'v*.*.*-staging' branch"
            exit 1
          fi
